
services:

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: codestar_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - codestar_red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_web
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - codestar_red

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: codestar_db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    networks:
      - codestar_red

  backend:
    build: ./backend
    container_name: nodejs_api
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: codestar_db
      DB_USER: admin
      DB_PASSWORD: admin123
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mailhog
    networks:
      - codestar_red


  mailhog:
    image: mailhog/mailhog
    container_name: mail_service
    restart: always
    ports:
      - "8025:8025"  
      - "1025:1025"  
    networks:
      - codestar_red

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
      - backend
    networks:
      - codestar_red

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - codestar_red

  mongo_express:
    image: mongo-express
    container_name: mongo_express_web
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongodb  
    ports:
      - "8083:8081"  
    depends_on:
      - mongodb
    networks:
      - codestar_red

volumes:
  mysql_data:
  wordpress_data:
  mongodb_data:

networks:
  codestar_red:
    driver: bridge